name: Update Status Badges

on:
  repository_dispatch:
    types: [created]

    
permissions:
    contents: write
    # pull-requests: read
    # issues: read
    # packages: read
    # security-events: read

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Status Badges
        run: |
          # Extract repository owner and name from environment variables
          REPO_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f1)
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)

          # Update the status badge URLs in README.md
          
          sed -i "s/Nick-Liou/$REPO_OWNER/g" README.md
          sed -i "s/Python_template/$REPO_NAME/g" README.md
        #   sed -i "s/Python_template_test/$REPO_NAME/g" README.md

        

        
      - name: Set up Git
        run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'

      - name: Commit and push changes
        run: |
            git add README.md
            git commit -m "Update README"
            git push
